Fix memory leaks
corazawaf/libcoraza pull request #7
Opened 2022-03-08 19:55 UTC by jptosso

Add waf free function

Free memory from tests

2022-03-08 21:59 UTC, airween requested changes
With my suggestions now I have this result:

```
==11057== LEAK SUMMARY:
==11057==    definitely lost: 0 bytes in 0 blocks
==11057==    indirectly lost: 0 bytes in 0 blocks
==11057==      possibly lost: 1,440 bytes in 5 blocks
==11057==    still reachable: 0 bytes in 0 blocks
==11057==         suppressed: 0 bytes in 0 blocks
```
The first to lines are fine, but we have to care the `possible lost` field too.

2022-03-08 21:59 UTC, airween commented on tests/simple_get.c
> +    free(uri);
This is not enough to free a `char **` variable. This is the right form:

```
    if (uri != NULL) {
        int i=0;
        while(uri[i] != NULL) {
            free(uri[i++]);
        }
        free(uri);
    }
```

2022-03-08 21:59 UTC, airween commented on tests/simple_get.c
> +    free(intervention);
This isn't enough to free a structure which has any pointer. You should call:

```
    if (intervention != NULL) {
        if (intervention->action != NULL) {
            free(intervention->action);
        }
        if (intervention->log != NULL) {
            free(intervention->log);
        }
        if (intervention->url != NULL) {
            free(intervention->url);
        }
        free(intervention);
    }
```
instead of a single `free(intervention)`.

2022-03-08 22:03 UTC, airween commented on tests/simple_get.c
> +    free(intervention);
Or you should implement a `coraza_free_intervention()` function, as you did in case of `coraza_free_waf()`.

Also would be fine to uniform the names, eg:
`coraza_free_waf()`
`coraza_free_intervention()` (coming soon :))
`coraza_free_transaction()` instead of `coraza_transaction_free()`. Or use this form in all cases.

This naming convention can help in the future if we want to use SWIG.

2022-03-09 00:24 UTC, jptosso commented on tests/simple_get.c
> +    free(intervention);
thank you Ervin, I will make the changes

2022-03-09 19:03 UTC, airween approved these changes

2022-03-09 19:04 UTC, merged